# Generated by Django 4.1.3 on 2023-09-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_number', models.IntegerField()),
                ('float_date', models.DateField()),
                ('floated_status', models.BooleanField()),
            ],
        ),
    ]
